{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: xlsxwriter in /home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages (3.1.2)\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: numpy in /home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages (1.24.3)\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: pandas in /home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages (2.0.2)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages (from pandas) (2.8.2)\n",
      "Requirement already satisfied: pytz>=2020.1 in /home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages (from pandas) (2022.7)\n",
      "Requirement already satisfied: tzdata>=2022.1 in /home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages (from pandas) (2023.3)\n",
      "Requirement already satisfied: numpy>=1.21.0 in /home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages (from pandas) (1.24.3)\n",
      "Requirement already satisfied: six>=1.5 in /home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: python-dateutil in /home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages (2.8.2)\n",
      "Requirement already satisfied: six>=1.5 in /home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages (from python-dateutil) (1.16.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: xlrd in /home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages (2.0.1)\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "\n",
      "Usage:   \n",
      "  /home/coenyka/miniconda3/envs/VSCode/bin/python -m pip uninstall [options] <package> ...\n",
      "  /home/coenyka/miniconda3/envs/VSCode/bin/python -m pip uninstall [options] -r <requirements file> ...\n",
      "\n",
      "no such option: -Y\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting logging\n",
      "  Using cached logging-0.4.9.6.tar.gz (96 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py egg_info\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[24 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 14, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages/setuptools/__init__.py\", line 8, in <module>\n",
      "  \u001b[31m   \u001b[0m     import _distutils_hack.override  # noqa: F401\n",
      "  \u001b[31m   \u001b[0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages/_distutils_hack/override.py\", line 1, in <module>\n",
      "  \u001b[31m   \u001b[0m     __import__('_distutils_hack').do_override()\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages/_distutils_hack/__init__.py\", line 77, in do_override\n",
      "  \u001b[31m   \u001b[0m     ensure_local_distutils()\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages/_distutils_hack/__init__.py\", line 63, in ensure_local_distutils\n",
      "  \u001b[31m   \u001b[0m     core = importlib.import_module('distutils.core')\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n",
      "  \u001b[31m   \u001b[0m     return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages/setuptools/_distutils/core.py\", line 22, in <module>\n",
      "  \u001b[31m   \u001b[0m     from .dist import Distribution\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages/setuptools/_distutils/dist.py\", line 12, in <module>\n",
      "  \u001b[31m   \u001b[0m     import logging\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-13roiy4t/logging_47d32a3961414692a55c01b4774d6569/logging/__init__.py\", line 618\n",
      "  \u001b[31m   \u001b[0m     raise NotImplementedError, 'emit must be implemented '\\\n",
      "  \u001b[31m   \u001b[0m                              ^\n",
      "  \u001b[31m   \u001b[0m SyntaxError: invalid syntax\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for details.\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "\n",
    "%pip install xlsxwriter\n",
    "%pip install numpy\n",
    "%pip install pandas\n",
    "%pip install python-dateutil\n",
    "%pip install xlrd\n",
    "%pip uninstall logger -Y\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting logging\n",
      "  Using cached logging-0.4.9.6.tar.gz (96 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py egg_info\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[24 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 14, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages/setuptools/__init__.py\", line 8, in <module>\n",
      "  \u001b[31m   \u001b[0m     import _distutils_hack.override  # noqa: F401\n",
      "  \u001b[31m   \u001b[0m     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages/_distutils_hack/override.py\", line 1, in <module>\n",
      "  \u001b[31m   \u001b[0m     __import__('_distutils_hack').do_override()\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages/_distutils_hack/__init__.py\", line 77, in do_override\n",
      "  \u001b[31m   \u001b[0m     ensure_local_distutils()\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages/_distutils_hack/__init__.py\", line 63, in ensure_local_distutils\n",
      "  \u001b[31m   \u001b[0m     core = importlib.import_module('distutils.core')\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/importlib/__init__.py\", line 126, in import_module\n",
      "  \u001b[31m   \u001b[0m     return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages/setuptools/_distutils/core.py\", line 22, in <module>\n",
      "  \u001b[31m   \u001b[0m     from .dist import Distribution\n",
      "  \u001b[31m   \u001b[0m   File \"/home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages/setuptools/_distutils/dist.py\", line 12, in <module>\n",
      "  \u001b[31m   \u001b[0m     import logging\n",
      "  \u001b[31m   \u001b[0m   File \"/tmp/pip-install-9svf3nhp/logging_69165af1b65c45138dc1d7e94f8152b1/logging/__init__.py\", line 618\n",
      "  \u001b[31m   \u001b[0m     raise NotImplementedError, 'emit must be implemented '\\\n",
      "  \u001b[31m   \u001b[0m                              ^\n",
      "  \u001b[31m   \u001b[0m SyntaxError: invalid syntax\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25h\u001b[1;31merror\u001b[0m: \u001b[1mmetadata-generation-failed\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m Encountered error while generating package metadata.\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This is an issue with the package mentioned above, not pip.\n",
      "\u001b[1;36mhint\u001b[0m: See above for details.\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Requirement already satisfied: tqdm in /home/coenyka/miniconda3/envs/VSCode/lib/python3.11/site-packages (4.65.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install logging -U\n",
    "%pip install tqdm -U"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "VSCode",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.3"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
